### ISSUE TITLE
Package for PyPI

### ISSUE THREAD

**Issue by theonewolf** [Xaroth/libzfs-python#1]
I'd love to have releases tagged and packaged for PyPI for easy install via `pip` on administrated systems.  This would greatly simplify the current deployment from source only model.

**Comment by Xaroth** [comment]
Hi,

While I would like to move this idea towards a pypy package, at this point I feel this library is nowhere near 'sane' to be used on anything remotely stable... as such, it would probably be unwise to have this package on pypy as it would encourage people to use this library and potentially ruin their data, which I am not a fan of.

If/when this library becomes more mature (i have some ideas on how to improve this, but it'll probably mean a complete rewrite of certain areas. Since the cffi part has to be locked to which libzfs the user is running, this library will need a system that is both resillient and stable enough that it can compensate for several environments (both linux and osx probably), and I am not yet at a stage where I can start working on that.

For now I will close this issue, but I will keep it in mind.
